/**
 * LoopBack Application
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;


/**
 * An asset named DiagHistory
 */
@ApiModel(description = "An asset named DiagHistory")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-22T10:20:50.211+07:00")
public class DiagHistory   {
  @SerializedName("$class")
  private String PropertyClass = "com.depa.blockchain.assets.DiagHistory";

  @SerializedName("diagId")
  private String diagId = null;

  @SerializedName("dateTimeService")
  private DateTime dateTimeService = null;

  @SerializedName("diagType")
  private String diagType = null;

  @SerializedName("diagName")
  private String diagName = null;

  @SerializedName("dateTimeUpdate")
  private DateTime dateTimeUpdate = null;

  @SerializedName("visit")
  private String visit = null;

  @SerializedName("doctorId")
  private String doctorId = null;

  @SerializedName("assetId")
  private String assetId = null;

  @SerializedName("patient")
  private String patient = null;

  @SerializedName("healthCareProvider")
  private String healthCareProvider = null;

  public DiagHistory PropertyClass(String PropertyClass) {
    this.PropertyClass = PropertyClass;
    return this;
  }

   /**
   * The class identifier for this type
   * @return PropertyClass
  **/
  @ApiModelProperty(example = "null", value = "The class identifier for this type")
  public String getPropertyClass() {
    return PropertyClass;
  }

  public void setPropertyClass(String PropertyClass) {
    this.PropertyClass = PropertyClass;
  }

  public DiagHistory diagId(String diagId) {
    this.diagId = diagId;
    return this;
  }

   /**
   * Get diagId
   * @return diagId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getDiagId() {
    return diagId;
  }

  public void setDiagId(String diagId) {
    this.diagId = diagId;
  }

  public DiagHistory dateTimeService(DateTime dateTimeService) {
    this.dateTimeService = dateTimeService;
    return this;
  }

   /**
   * Get dateTimeService
   * @return dateTimeService
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public DateTime getDateTimeService() {
    return dateTimeService;
  }

  public void setDateTimeService(DateTime dateTimeService) {
    this.dateTimeService = dateTimeService;
  }

  public DiagHistory diagType(String diagType) {
    this.diagType = diagType;
    return this;
  }

   /**
   * Get diagType
   * @return diagType
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getDiagType() {
    return diagType;
  }

  public void setDiagType(String diagType) {
    this.diagType = diagType;
  }

  public DiagHistory diagName(String diagName) {
    this.diagName = diagName;
    return this;
  }

   /**
   * Get diagName
   * @return diagName
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getDiagName() {
    return diagName;
  }

  public void setDiagName(String diagName) {
    this.diagName = diagName;
  }

  public DiagHistory dateTimeUpdate(DateTime dateTimeUpdate) {
    this.dateTimeUpdate = dateTimeUpdate;
    return this;
  }

   /**
   * Get dateTimeUpdate
   * @return dateTimeUpdate
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public DateTime getDateTimeUpdate() {
    return dateTimeUpdate;
  }

  public void setDateTimeUpdate(DateTime dateTimeUpdate) {
    this.dateTimeUpdate = dateTimeUpdate;
  }

  public DiagHistory visit(String visit) {
    this.visit = visit;
    return this;
  }

   /**
   * The identifier of an instance of visit
   * @return visit
  **/
  @ApiModelProperty(example = "null", required = true, value = "The identifier of an instance of visit")
  public String getVisit() {
    return visit;
  }

  public void setVisit(String visit) {
    this.visit = visit;
  }

  public DiagHistory doctorId(String doctorId) {
    this.doctorId = doctorId;
    return this;
  }

   /**
   * The identifier of an instance of doctorId
   * @return doctorId
  **/
  @ApiModelProperty(example = "null", value = "The identifier of an instance of doctorId")
  public String getDoctorId() {
    return doctorId;
  }

  public void setDoctorId(String doctorId) {
    this.doctorId = doctorId;
  }

  public DiagHistory assetId(String assetId) {
    this.assetId = assetId;
    return this;
  }

   /**
   * The instance identifier for this type
   * @return assetId
  **/
  @ApiModelProperty(example = "null", required = true, value = "The instance identifier for this type")
  public String getAssetId() {
    return assetId;
  }

  public void setAssetId(String assetId) {
    this.assetId = assetId;
  }

  public DiagHistory patient(String patient) {
    this.patient = patient;
    return this;
  }

   /**
   * The identifier of an instance of patient
   * @return patient
  **/
  @ApiModelProperty(example = "null", required = true, value = "The identifier of an instance of patient")
  public String getPatient() {
    return patient;
  }

  public void setPatient(String patient) {
    this.patient = patient;
  }

  public DiagHistory healthCareProvider(String healthCareProvider) {
    this.healthCareProvider = healthCareProvider;
    return this;
  }

   /**
   * The identifier of an instance of healthCareProvider
   * @return healthCareProvider
  **/
  @ApiModelProperty(example = "null", required = true, value = "The identifier of an instance of healthCareProvider")
  public String getHealthCareProvider() {
    return healthCareProvider;
  }

  public void setHealthCareProvider(String healthCareProvider) {
    this.healthCareProvider = healthCareProvider;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DiagHistory diagHistory = (DiagHistory) o;
    return Objects.equals(this.PropertyClass, diagHistory.PropertyClass) &&
        Objects.equals(this.diagId, diagHistory.diagId) &&
        Objects.equals(this.dateTimeService, diagHistory.dateTimeService) &&
        Objects.equals(this.diagType, diagHistory.diagType) &&
        Objects.equals(this.diagName, diagHistory.diagName) &&
        Objects.equals(this.dateTimeUpdate, diagHistory.dateTimeUpdate) &&
        Objects.equals(this.visit, diagHistory.visit) &&
        Objects.equals(this.doctorId, diagHistory.doctorId) &&
        Objects.equals(this.assetId, diagHistory.assetId) &&
        Objects.equals(this.patient, diagHistory.patient) &&
        Objects.equals(this.healthCareProvider, diagHistory.healthCareProvider);
  }

  @Override
  public int hashCode() {
    return Objects.hash(PropertyClass, diagId, dateTimeService, diagType, diagName, dateTimeUpdate, visit, doctorId, assetId, patient, healthCareProvider);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DiagHistory {\n");
    
    sb.append("    PropertyClass: ").append(toIndentedString(PropertyClass)).append("\n");
    sb.append("    diagId: ").append(toIndentedString(diagId)).append("\n");
    sb.append("    dateTimeService: ").append(toIndentedString(dateTimeService)).append("\n");
    sb.append("    diagType: ").append(toIndentedString(diagType)).append("\n");
    sb.append("    diagName: ").append(toIndentedString(diagName)).append("\n");
    sb.append("    dateTimeUpdate: ").append(toIndentedString(dateTimeUpdate)).append("\n");
    sb.append("    visit: ").append(toIndentedString(visit)).append("\n");
    sb.append("    doctorId: ").append(toIndentedString(doctorId)).append("\n");
    sb.append("    assetId: ").append(toIndentedString(assetId)).append("\n");
    sb.append("    patient: ").append(toIndentedString(patient)).append("\n");
    sb.append("    healthCareProvider: ").append(toIndentedString(healthCareProvider)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

