/**
 * LoopBack Application
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;


/**
 * A participant named Doctor
 */
@ApiModel(description = "A participant named Doctor")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-22T10:20:50.211+07:00")
public class Doctor   {
  @SerializedName("$class")
  private String PropertyClass = "com.depa.blockchain.core.Doctor";

  @SerializedName("doctorId")
  private String doctorId = null;

  @SerializedName("prename")
  private String prename = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("surname")
  private String surname = null;

  @SerializedName("phone")
  private String phone = null;

  @SerializedName("mobilePhone")
  private String mobilePhone = null;

  @SerializedName("specialty")
  private String specialty = null;

  @SerializedName("dateTimeUpdate")
  private DateTime dateTimeUpdate = null;

  @SerializedName("sex")
  private String sex = null;

  @SerializedName("role")
  private String role = null;

  @SerializedName("picture")
  private String picture = null;

  @SerializedName("healthCareProvider")
  private List<String> healthCareProvider = new ArrayList<String>();

  public Doctor PropertyClass(String PropertyClass) {
    this.PropertyClass = PropertyClass;
    return this;
  }

   /**
   * The class identifier for this type
   * @return PropertyClass
  **/
  @ApiModelProperty(example = "null", value = "The class identifier for this type")
  public String getPropertyClass() {
    return PropertyClass;
  }

  public void setPropertyClass(String PropertyClass) {
    this.PropertyClass = PropertyClass;
  }

  public Doctor doctorId(String doctorId) {
    this.doctorId = doctorId;
    return this;
  }

   /**
   * The instance identifier for this type
   * @return doctorId
  **/
  @ApiModelProperty(example = "null", required = true, value = "The instance identifier for this type")
  public String getDoctorId() {
    return doctorId;
  }

  public void setDoctorId(String doctorId) {
    this.doctorId = doctorId;
  }

  public Doctor prename(String prename) {
    this.prename = prename;
    return this;
  }

   /**
   * Get prename
   * @return prename
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getPrename() {
    return prename;
  }

  public void setPrename(String prename) {
    this.prename = prename;
  }

  public Doctor name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Doctor surname(String surname) {
    this.surname = surname;
    return this;
  }

   /**
   * Get surname
   * @return surname
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getSurname() {
    return surname;
  }

  public void setSurname(String surname) {
    this.surname = surname;
  }

  public Doctor phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public Doctor mobilePhone(String mobilePhone) {
    this.mobilePhone = mobilePhone;
    return this;
  }

   /**
   * Get mobilePhone
   * @return mobilePhone
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMobilePhone() {
    return mobilePhone;
  }

  public void setMobilePhone(String mobilePhone) {
    this.mobilePhone = mobilePhone;
  }

  public Doctor specialty(String specialty) {
    this.specialty = specialty;
    return this;
  }

   /**
   * Get specialty
   * @return specialty
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSpecialty() {
    return specialty;
  }

  public void setSpecialty(String specialty) {
    this.specialty = specialty;
  }

  public Doctor dateTimeUpdate(DateTime dateTimeUpdate) {
    this.dateTimeUpdate = dateTimeUpdate;
    return this;
  }

   /**
   * Get dateTimeUpdate
   * @return dateTimeUpdate
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public DateTime getDateTimeUpdate() {
    return dateTimeUpdate;
  }

  public void setDateTimeUpdate(DateTime dateTimeUpdate) {
    this.dateTimeUpdate = dateTimeUpdate;
  }

  public Doctor sex(String sex) {
    this.sex = sex;
    return this;
  }

   /**
   * Get sex
   * @return sex
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSex() {
    return sex;
  }

  public void setSex(String sex) {
    this.sex = sex;
  }

  public Doctor role(String role) {
    this.role = role;
    return this;
  }

   /**
   * Get role
   * @return role
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRole() {
    return role;
  }

  public void setRole(String role) {
    this.role = role;
  }

  public Doctor picture(String picture) {
    this.picture = picture;
    return this;
  }

   /**
   * Get picture
   * @return picture
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPicture() {
    return picture;
  }

  public void setPicture(String picture) {
    this.picture = picture;
  }

  public Doctor healthCareProvider(List<String> healthCareProvider) {
    this.healthCareProvider = healthCareProvider;
    return this;
  }

  public Doctor addHealthCareProviderItem(String healthCareProviderItem) {
    this.healthCareProvider.add(healthCareProviderItem);
    return this;
  }

   /**
   * The identifier of an instance of healthCareProvider
   * @return healthCareProvider
  **/
  @ApiModelProperty(example = "null", required = true, value = "The identifier of an instance of healthCareProvider")
  public List<String> getHealthCareProvider() {
    return healthCareProvider;
  }

  public void setHealthCareProvider(List<String> healthCareProvider) {
    this.healthCareProvider = healthCareProvider;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Doctor doctor = (Doctor) o;
    return Objects.equals(this.PropertyClass, doctor.PropertyClass) &&
        Objects.equals(this.doctorId, doctor.doctorId) &&
        Objects.equals(this.prename, doctor.prename) &&
        Objects.equals(this.name, doctor.name) &&
        Objects.equals(this.surname, doctor.surname) &&
        Objects.equals(this.phone, doctor.phone) &&
        Objects.equals(this.mobilePhone, doctor.mobilePhone) &&
        Objects.equals(this.specialty, doctor.specialty) &&
        Objects.equals(this.dateTimeUpdate, doctor.dateTimeUpdate) &&
        Objects.equals(this.sex, doctor.sex) &&
        Objects.equals(this.role, doctor.role) &&
        Objects.equals(this.picture, doctor.picture) &&
        Objects.equals(this.healthCareProvider, doctor.healthCareProvider);
  }

  @Override
  public int hashCode() {
    return Objects.hash(PropertyClass, doctorId, prename, name, surname, phone, mobilePhone, specialty, dateTimeUpdate, sex, role, picture, healthCareProvider);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Doctor {\n");
    
    sb.append("    PropertyClass: ").append(toIndentedString(PropertyClass)).append("\n");
    sb.append("    doctorId: ").append(toIndentedString(doctorId)).append("\n");
    sb.append("    prename: ").append(toIndentedString(prename)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    surname: ").append(toIndentedString(surname)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    mobilePhone: ").append(toIndentedString(mobilePhone)).append("\n");
    sb.append("    specialty: ").append(toIndentedString(specialty)).append("\n");
    sb.append("    dateTimeUpdate: ").append(toIndentedString(dateTimeUpdate)).append("\n");
    sb.append("    sex: ").append(toIndentedString(sex)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    picture: ").append(toIndentedString(picture)).append("\n");
    sb.append("    healthCareProvider: ").append(toIndentedString(healthCareProvider)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

