/**
 * LoopBack Application
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;


/**
 * An asset named DrugHistory
 */
@ApiModel(description = "An asset named DrugHistory")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-22T10:20:50.211+07:00")
public class DrugHistory   {
  @SerializedName("$class")
  private String PropertyClass = "com.depa.blockchain.assets.DrugHistory";

  @SerializedName("drugCode")
  private String drugCode = null;

  @SerializedName("drugName")
  private String drugName = null;

  @SerializedName("dosage")
  private String dosage = null;

  @SerializedName("unit")
  private String unit = null;

  @SerializedName("frequency")
  private String frequency = null;

  @SerializedName("dateTimeUpdate")
  private DateTime dateTimeUpdate = null;

  @SerializedName("visit")
  private String visit = null;

  @SerializedName("doctorId")
  private String doctorId = null;

  @SerializedName("assetId")
  private String assetId = null;

  @SerializedName("authorized")
  private List<String> authorized = new ArrayList<String>();

  @SerializedName("patient")
  private String patient = null;

  @SerializedName("healthCareProvider")
  private String healthCareProvider = null;

  public DrugHistory PropertyClass(String PropertyClass) {
    this.PropertyClass = PropertyClass;
    return this;
  }

   /**
   * The class identifier for this type
   * @return PropertyClass
  **/
  @ApiModelProperty(example = "null", value = "The class identifier for this type")
  public String getPropertyClass() {
    return PropertyClass;
  }

  public void setPropertyClass(String PropertyClass) {
    this.PropertyClass = PropertyClass;
  }

  public DrugHistory drugCode(String drugCode) {
    this.drugCode = drugCode;
    return this;
  }

   /**
   * Get drugCode
   * @return drugCode
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getDrugCode() {
    return drugCode;
  }

  public void setDrugCode(String drugCode) {
    this.drugCode = drugCode;
  }

  public DrugHistory drugName(String drugName) {
    this.drugName = drugName;
    return this;
  }

   /**
   * Get drugName
   * @return drugName
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getDrugName() {
    return drugName;
  }

  public void setDrugName(String drugName) {
    this.drugName = drugName;
  }

  public DrugHistory dosage(String dosage) {
    this.dosage = dosage;
    return this;
  }

   /**
   * Get dosage
   * @return dosage
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getDosage() {
    return dosage;
  }

  public void setDosage(String dosage) {
    this.dosage = dosage;
  }

  public DrugHistory unit(String unit) {
    this.unit = unit;
    return this;
  }

   /**
   * Get unit
   * @return unit
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getUnit() {
    return unit;
  }

  public void setUnit(String unit) {
    this.unit = unit;
  }

  public DrugHistory frequency(String frequency) {
    this.frequency = frequency;
    return this;
  }

   /**
   * Get frequency
   * @return frequency
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getFrequency() {
    return frequency;
  }

  public void setFrequency(String frequency) {
    this.frequency = frequency;
  }

  public DrugHistory dateTimeUpdate(DateTime dateTimeUpdate) {
    this.dateTimeUpdate = dateTimeUpdate;
    return this;
  }

   /**
   * Get dateTimeUpdate
   * @return dateTimeUpdate
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public DateTime getDateTimeUpdate() {
    return dateTimeUpdate;
  }

  public void setDateTimeUpdate(DateTime dateTimeUpdate) {
    this.dateTimeUpdate = dateTimeUpdate;
  }

  public DrugHistory visit(String visit) {
    this.visit = visit;
    return this;
  }

   /**
   * The identifier of an instance of visit
   * @return visit
  **/
  @ApiModelProperty(example = "null", required = true, value = "The identifier of an instance of visit")
  public String getVisit() {
    return visit;
  }

  public void setVisit(String visit) {
    this.visit = visit;
  }

  public DrugHistory doctorId(String doctorId) {
    this.doctorId = doctorId;
    return this;
  }

   /**
   * The identifier of an instance of doctorId
   * @return doctorId
  **/
  @ApiModelProperty(example = "null", value = "The identifier of an instance of doctorId")
  public String getDoctorId() {
    return doctorId;
  }

  public void setDoctorId(String doctorId) {
    this.doctorId = doctorId;
  }

  public DrugHistory assetId(String assetId) {
    this.assetId = assetId;
    return this;
  }

   /**
   * The instance identifier for this type
   * @return assetId
  **/
  @ApiModelProperty(example = "null", required = true, value = "The instance identifier for this type")
  public String getAssetId() {
    return assetId;
  }

  public void setAssetId(String assetId) {
    this.assetId = assetId;
  }

  public DrugHistory authorized(List<String> authorized) {
    this.authorized = authorized;
    return this;
  }

  public DrugHistory addAuthorizedItem(String authorizedItem) {
    this.authorized.add(authorizedItem);
    return this;
  }

   /**
   * Get authorized
   * @return authorized
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getAuthorized() {
    return authorized;
  }

  public void setAuthorized(List<String> authorized) {
    this.authorized = authorized;
  }

  public DrugHistory patient(String patient) {
    this.patient = patient;
    return this;
  }

   /**
   * The identifier of an instance of patient
   * @return patient
  **/
  @ApiModelProperty(example = "null", required = true, value = "The identifier of an instance of patient")
  public String getPatient() {
    return patient;
  }

  public void setPatient(String patient) {
    this.patient = patient;
  }

  public DrugHistory healthCareProvider(String healthCareProvider) {
    this.healthCareProvider = healthCareProvider;
    return this;
  }

   /**
   * The identifier of an instance of healthCareProvider
   * @return healthCareProvider
  **/
  @ApiModelProperty(example = "null", required = true, value = "The identifier of an instance of healthCareProvider")
  public String getHealthCareProvider() {
    return healthCareProvider;
  }

  public void setHealthCareProvider(String healthCareProvider) {
    this.healthCareProvider = healthCareProvider;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DrugHistory drugHistory = (DrugHistory) o;
    return Objects.equals(this.PropertyClass, drugHistory.PropertyClass) &&
        Objects.equals(this.drugCode, drugHistory.drugCode) &&
        Objects.equals(this.drugName, drugHistory.drugName) &&
        Objects.equals(this.dosage, drugHistory.dosage) &&
        Objects.equals(this.unit, drugHistory.unit) &&
        Objects.equals(this.frequency, drugHistory.frequency) &&
        Objects.equals(this.dateTimeUpdate, drugHistory.dateTimeUpdate) &&
        Objects.equals(this.visit, drugHistory.visit) &&
        Objects.equals(this.doctorId, drugHistory.doctorId) &&
        Objects.equals(this.assetId, drugHistory.assetId) &&
        Objects.equals(this.authorized, drugHistory.authorized) &&
        Objects.equals(this.patient, drugHistory.patient) &&
        Objects.equals(this.healthCareProvider, drugHistory.healthCareProvider);
  }

  @Override
  public int hashCode() {
    return Objects.hash(PropertyClass, drugCode, drugName, dosage, unit, frequency, dateTimeUpdate, visit, doctorId, assetId, authorized, patient, healthCareProvider);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DrugHistory {\n");
    
    sb.append("    PropertyClass: ").append(toIndentedString(PropertyClass)).append("\n");
    sb.append("    drugCode: ").append(toIndentedString(drugCode)).append("\n");
    sb.append("    drugName: ").append(toIndentedString(drugName)).append("\n");
    sb.append("    dosage: ").append(toIndentedString(dosage)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("    frequency: ").append(toIndentedString(frequency)).append("\n");
    sb.append("    dateTimeUpdate: ").append(toIndentedString(dateTimeUpdate)).append("\n");
    sb.append("    visit: ").append(toIndentedString(visit)).append("\n");
    sb.append("    doctorId: ").append(toIndentedString(doctorId)).append("\n");
    sb.append("    assetId: ").append(toIndentedString(assetId)).append("\n");
    sb.append("    authorized: ").append(toIndentedString(authorized)).append("\n");
    sb.append("    patient: ").append(toIndentedString(patient)).append("\n");
    sb.append("    healthCareProvider: ").append(toIndentedString(healthCareProvider)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

