/**
 * LoopBack Application
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * A participant named HealthCareProvider
 */
@ApiModel(description = "A participant named HealthCareProvider")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-22T10:20:50.211+07:00")
public class HealthCareProvider   {
  @SerializedName("$class")
  private String PropertyClass = "com.depa.blockchain.core.HealthCareProvider";

  @SerializedName("healthCareProviderId")
  private String healthCareProviderId = null;

  @SerializedName("healthCareProviderName")
  private String healthCareProviderName = null;

  @SerializedName("erPhone")
  private String erPhone = null;

  @SerializedName("primaryCare")
  private String primaryCare = null;

  @SerializedName("dateTimeUpdate")
  private String dateTimeUpdate = null;

  public HealthCareProvider PropertyClass(String PropertyClass) {
    this.PropertyClass = PropertyClass;
    return this;
  }

   /**
   * The class identifier for this type
   * @return PropertyClass
  **/
  @ApiModelProperty(example = "null", value = "The class identifier for this type")
  public String getPropertyClass() {
    return PropertyClass;
  }

  public void setPropertyClass(String PropertyClass) {
    this.PropertyClass = PropertyClass;
  }

  public HealthCareProvider healthCareProviderId(String healthCareProviderId) {
    this.healthCareProviderId = healthCareProviderId;
    return this;
  }

   /**
   * The instance identifier for this type
   * @return healthCareProviderId
  **/
  @ApiModelProperty(example = "null", required = true, value = "The instance identifier for this type")
  public String getHealthCareProviderId() {
    return healthCareProviderId;
  }

  public void setHealthCareProviderId(String healthCareProviderId) {
    this.healthCareProviderId = healthCareProviderId;
  }

  public HealthCareProvider healthCareProviderName(String healthCareProviderName) {
    this.healthCareProviderName = healthCareProviderName;
    return this;
  }

   /**
   * Get healthCareProviderName
   * @return healthCareProviderName
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getHealthCareProviderName() {
    return healthCareProviderName;
  }

  public void setHealthCareProviderName(String healthCareProviderName) {
    this.healthCareProviderName = healthCareProviderName;
  }

  public HealthCareProvider erPhone(String erPhone) {
    this.erPhone = erPhone;
    return this;
  }

   /**
   * Get erPhone
   * @return erPhone
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getErPhone() {
    return erPhone;
  }

  public void setErPhone(String erPhone) {
    this.erPhone = erPhone;
  }

  public HealthCareProvider primaryCare(String primaryCare) {
    this.primaryCare = primaryCare;
    return this;
  }

   /**
   * Get primaryCare
   * @return primaryCare
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPrimaryCare() {
    return primaryCare;
  }

  public void setPrimaryCare(String primaryCare) {
    this.primaryCare = primaryCare;
  }

  public HealthCareProvider dateTimeUpdate(String dateTimeUpdate) {
    this.dateTimeUpdate = dateTimeUpdate;
    return this;
  }

   /**
   * Get dateTimeUpdate
   * @return dateTimeUpdate
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getDateTimeUpdate() {
    return dateTimeUpdate;
  }

  public void setDateTimeUpdate(String dateTimeUpdate) {
    this.dateTimeUpdate = dateTimeUpdate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HealthCareProvider healthCareProvider = (HealthCareProvider) o;
    return Objects.equals(this.PropertyClass, healthCareProvider.PropertyClass) &&
        Objects.equals(this.healthCareProviderId, healthCareProvider.healthCareProviderId) &&
        Objects.equals(this.healthCareProviderName, healthCareProvider.healthCareProviderName) &&
        Objects.equals(this.erPhone, healthCareProvider.erPhone) &&
        Objects.equals(this.primaryCare, healthCareProvider.primaryCare) &&
        Objects.equals(this.dateTimeUpdate, healthCareProvider.dateTimeUpdate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(PropertyClass, healthCareProviderId, healthCareProviderName, erPhone, primaryCare, dateTimeUpdate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HealthCareProvider {\n");
    
    sb.append("    PropertyClass: ").append(toIndentedString(PropertyClass)).append("\n");
    sb.append("    healthCareProviderId: ").append(toIndentedString(healthCareProviderId)).append("\n");
    sb.append("    healthCareProviderName: ").append(toIndentedString(healthCareProviderName)).append("\n");
    sb.append("    erPhone: ").append(toIndentedString(erPhone)).append("\n");
    sb.append("    primaryCare: ").append(toIndentedString(primaryCare)).append("\n");
    sb.append("    dateTimeUpdate: ").append(toIndentedString(dateTimeUpdate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

