/**
 * LoopBack Application
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;


/**
 * A concept named Lifestyle
 */
@ApiModel(description = "A concept named Lifestyle")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-22T10:20:50.211+07:00")
public class Lifestyle   {
  @SerializedName("$class")
  private String PropertyClass = "com.depa.blockchain.core.Lifestyle";

  @SerializedName("lifeStyleId")
  private String lifeStyleId = null;

  @SerializedName("alcoholism")
  private String alcoholism = null;

  @SerializedName("drinkOfWeek")
  private String drinkOfWeek = null;

  @SerializedName("smoking")
  private String smoking = null;

  @SerializedName("packsPerDay")
  private String packsPerDay = null;

  @SerializedName("dateTimeUpdate")
  private DateTime dateTimeUpdate = null;

  @SerializedName("id")
  private String id = null;

  public Lifestyle PropertyClass(String PropertyClass) {
    this.PropertyClass = PropertyClass;
    return this;
  }

   /**
   * The class identifier for this type
   * @return PropertyClass
  **/
  @ApiModelProperty(example = "null", value = "The class identifier for this type")
  public String getPropertyClass() {
    return PropertyClass;
  }

  public void setPropertyClass(String PropertyClass) {
    this.PropertyClass = PropertyClass;
  }

  public Lifestyle lifeStyleId(String lifeStyleId) {
    this.lifeStyleId = lifeStyleId;
    return this;
  }

   /**
   * Get lifeStyleId
   * @return lifeStyleId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getLifeStyleId() {
    return lifeStyleId;
  }

  public void setLifeStyleId(String lifeStyleId) {
    this.lifeStyleId = lifeStyleId;
  }

  public Lifestyle alcoholism(String alcoholism) {
    this.alcoholism = alcoholism;
    return this;
  }

   /**
   * Get alcoholism
   * @return alcoholism
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getAlcoholism() {
    return alcoholism;
  }

  public void setAlcoholism(String alcoholism) {
    this.alcoholism = alcoholism;
  }

  public Lifestyle drinkOfWeek(String drinkOfWeek) {
    this.drinkOfWeek = drinkOfWeek;
    return this;
  }

   /**
   * Get drinkOfWeek
   * @return drinkOfWeek
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getDrinkOfWeek() {
    return drinkOfWeek;
  }

  public void setDrinkOfWeek(String drinkOfWeek) {
    this.drinkOfWeek = drinkOfWeek;
  }

  public Lifestyle smoking(String smoking) {
    this.smoking = smoking;
    return this;
  }

   /**
   * Get smoking
   * @return smoking
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getSmoking() {
    return smoking;
  }

  public void setSmoking(String smoking) {
    this.smoking = smoking;
  }

  public Lifestyle packsPerDay(String packsPerDay) {
    this.packsPerDay = packsPerDay;
    return this;
  }

   /**
   * Get packsPerDay
   * @return packsPerDay
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getPacksPerDay() {
    return packsPerDay;
  }

  public void setPacksPerDay(String packsPerDay) {
    this.packsPerDay = packsPerDay;
  }

  public Lifestyle dateTimeUpdate(DateTime dateTimeUpdate) {
    this.dateTimeUpdate = dateTimeUpdate;
    return this;
  }

   /**
   * Get dateTimeUpdate
   * @return dateTimeUpdate
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public DateTime getDateTimeUpdate() {
    return dateTimeUpdate;
  }

  public void setDateTimeUpdate(DateTime dateTimeUpdate) {
    this.dateTimeUpdate = dateTimeUpdate;
  }

  public Lifestyle id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Lifestyle lifestyle = (Lifestyle) o;
    return Objects.equals(this.PropertyClass, lifestyle.PropertyClass) &&
        Objects.equals(this.lifeStyleId, lifestyle.lifeStyleId) &&
        Objects.equals(this.alcoholism, lifestyle.alcoholism) &&
        Objects.equals(this.drinkOfWeek, lifestyle.drinkOfWeek) &&
        Objects.equals(this.smoking, lifestyle.smoking) &&
        Objects.equals(this.packsPerDay, lifestyle.packsPerDay) &&
        Objects.equals(this.dateTimeUpdate, lifestyle.dateTimeUpdate) &&
        Objects.equals(this.id, lifestyle.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(PropertyClass, lifeStyleId, alcoholism, drinkOfWeek, smoking, packsPerDay, dateTimeUpdate, id);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Lifestyle {\n");
    
    sb.append("    PropertyClass: ").append(toIndentedString(PropertyClass)).append("\n");
    sb.append("    lifeStyleId: ").append(toIndentedString(lifeStyleId)).append("\n");
    sb.append("    alcoholism: ").append(toIndentedString(alcoholism)).append("\n");
    sb.append("    drinkOfWeek: ").append(toIndentedString(drinkOfWeek)).append("\n");
    sb.append("    smoking: ").append(toIndentedString(smoking)).append("\n");
    sb.append("    packsPerDay: ").append(toIndentedString(packsPerDay)).append("\n");
    sb.append("    dateTimeUpdate: ").append(toIndentedString(dateTimeUpdate)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

