/**
 * LoopBack Application
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;


/**
 * An asset named PermissionLog
 */
@ApiModel(description = "An asset named PermissionLog")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-22T10:20:50.211+07:00")
public class PermissionLog   {
  @SerializedName("$class")
  private String PropertyClass = "com.depa.blockchain.core.PermissionLog";

  @SerializedName("permissionLogId")
  private String permissionLogId = null;

  /**
   * Gets or Sets permissionType
   */
  public enum PermissionTypeEnum {
    @SerializedName("REQUEST")
    REQUEST("REQUEST"),
    
    @SerializedName("GRANT")
    GRANT("GRANT"),
    
    @SerializedName("DENY")
    DENY("DENY"),
    
    @SerializedName("REVOKE")
    REVOKE("REVOKE");

    private String value;

    PermissionTypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("permissionType")
  private PermissionTypeEnum permissionType = null;

  @SerializedName("actionDateTime")
  private DateTime actionDateTime = null;

  @SerializedName("patient")
  private String patient = null;

  @SerializedName("healthCareProvider")
  private String healthCareProvider = null;

  public PermissionLog PropertyClass(String PropertyClass) {
    this.PropertyClass = PropertyClass;
    return this;
  }

   /**
   * The class identifier for this type
   * @return PropertyClass
  **/
  @ApiModelProperty(example = "null", value = "The class identifier for this type")
  public String getPropertyClass() {
    return PropertyClass;
  }

  public void setPropertyClass(String PropertyClass) {
    this.PropertyClass = PropertyClass;
  }

  public PermissionLog permissionLogId(String permissionLogId) {
    this.permissionLogId = permissionLogId;
    return this;
  }

   /**
   * The instance identifier for this type
   * @return permissionLogId
  **/
  @ApiModelProperty(example = "null", required = true, value = "The instance identifier for this type")
  public String getPermissionLogId() {
    return permissionLogId;
  }

  public void setPermissionLogId(String permissionLogId) {
    this.permissionLogId = permissionLogId;
  }

  public PermissionLog permissionType(PermissionTypeEnum permissionType) {
    this.permissionType = permissionType;
    return this;
  }

   /**
   * Get permissionType
   * @return permissionType
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public PermissionTypeEnum getPermissionType() {
    return permissionType;
  }

  public void setPermissionType(PermissionTypeEnum permissionType) {
    this.permissionType = permissionType;
  }

  public PermissionLog actionDateTime(DateTime actionDateTime) {
    this.actionDateTime = actionDateTime;
    return this;
  }

   /**
   * Get actionDateTime
   * @return actionDateTime
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public DateTime getActionDateTime() {
    return actionDateTime;
  }

  public void setActionDateTime(DateTime actionDateTime) {
    this.actionDateTime = actionDateTime;
  }

  public PermissionLog patient(String patient) {
    this.patient = patient;
    return this;
  }

   /**
   * The identifier of an instance of patient
   * @return patient
  **/
  @ApiModelProperty(example = "null", required = true, value = "The identifier of an instance of patient")
  public String getPatient() {
    return patient;
  }

  public void setPatient(String patient) {
    this.patient = patient;
  }

  public PermissionLog healthCareProvider(String healthCareProvider) {
    this.healthCareProvider = healthCareProvider;
    return this;
  }

   /**
   * The identifier of an instance of healthCareProvider
   * @return healthCareProvider
  **/
  @ApiModelProperty(example = "null", required = true, value = "The identifier of an instance of healthCareProvider")
  public String getHealthCareProvider() {
    return healthCareProvider;
  }

  public void setHealthCareProvider(String healthCareProvider) {
    this.healthCareProvider = healthCareProvider;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PermissionLog permissionLog = (PermissionLog) o;
    return Objects.equals(this.PropertyClass, permissionLog.PropertyClass) &&
        Objects.equals(this.permissionLogId, permissionLog.permissionLogId) &&
        Objects.equals(this.permissionType, permissionLog.permissionType) &&
        Objects.equals(this.actionDateTime, permissionLog.actionDateTime) &&
        Objects.equals(this.patient, permissionLog.patient) &&
        Objects.equals(this.healthCareProvider, permissionLog.healthCareProvider);
  }

  @Override
  public int hashCode() {
    return Objects.hash(PropertyClass, permissionLogId, permissionType, actionDateTime, patient, healthCareProvider);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PermissionLog {\n");
    
    sb.append("    PropertyClass: ").append(toIndentedString(PropertyClass)).append("\n");
    sb.append("    permissionLogId: ").append(toIndentedString(permissionLogId)).append("\n");
    sb.append("    permissionType: ").append(toIndentedString(permissionType)).append("\n");
    sb.append("    actionDateTime: ").append(toIndentedString(actionDateTime)).append("\n");
    sb.append("    patient: ").append(toIndentedString(patient)).append("\n");
    sb.append("    healthCareProvider: ").append(toIndentedString(healthCareProvider)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

