/**
 * LoopBack Application
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.CheckupHistory;
import io.swagger.client.model.DiagHistory;
import io.swagger.client.model.DrugHistory;
import io.swagger.client.model.Patient;
import io.swagger.client.model.ProcedureHistory;
import io.swagger.client.model.ProtectedAsset;
import io.swagger.client.model.ServiceHistory;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for QueryApi
 */
public class QueryApiTest {

    private final QueryApi api = new QueryApi();

    
    /**
     * Show all checkup history for specified patient
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryListAllCheckupHistoryOfPatientTest() throws ApiException {
        String patientIdParam = null;
        // List<CheckupHistory> response = api.queryListAllCheckupHistoryOfPatient(patientIdParam);

        // TODO: test validations
    }
    
    /**
     * Show all diagnostic history for specified patient
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryListAllDiagHistoryOfPatientTest() throws ApiException {
        String patientIdParam = null;
        // List<DiagHistory> response = api.queryListAllDiagHistoryOfPatient(patientIdParam);

        // TODO: test validations
    }
    
    /**
     * Show all drug history for specified patient
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryListAllDrugHistoryOfPatientTest() throws ApiException {
        String patientIdParam = null;
        // List<DrugHistory> response = api.queryListAllDrugHistoryOfPatient(patientIdParam);

        // TODO: test validations
    }
    
    /**
     * List all valid permission grant
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryListAllGrantedPermissionTest() throws ApiException {
        // List<Patient> response = api.queryListAllGrantedPermission();

        // TODO: test validations
    }
    
    /**
     * Get list of pending permission request of patient
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryListAllPendingPermissionRequestTest() throws ApiException {
        // List<Patient> response = api.queryListAllPendingPermissionRequest();

        // TODO: test validations
    }
    
    /**
     * Show all procedure history for specified patient
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryListAllProcedureHistoryOfPatientTest() throws ApiException {
        String patientIdParam = null;
        // List<ProcedureHistory> response = api.queryListAllProcedureHistoryOfPatient(patientIdParam);

        // TODO: test validations
    }
    
    /**
     * List all protected assets
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryListAllProtectedAssetsTest() throws ApiException {
        // List<ProtectedAsset> response = api.queryListAllProtectedAssets();

        // TODO: test validations
    }
    
    /**
     * Show all service history for specified patient
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryListAllServiceHistoryOfPatientTest() throws ApiException {
        String patientIdParam = null;
        // List<ServiceHistory> response = api.queryListAllServiceHistoryOfPatient(patientIdParam);

        // TODO: test validations
    }
    
}
