/**
 * LoopBack Application
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.BindIdentityRequest;
import io.swagger.client.model.IssueIdentityRequest;
import java.io.File;
import io.swagger.client.model.PingResponse;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SystemApi
 */
public class SystemApiTest {

    private final SystemApi api = new SystemApi();

    
    /**
     * Bind an identity to the specified participant
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemBindIdentityTest() throws ApiException {
        BindIdentityRequest data = null;
        // api.systemBindIdentity(data);

        // TODO: test validations
    }
    
    /**
     * Get all Historian Records from the Historian
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemGetAllHistorianRecordsTest() throws ApiException {
        // List<Object> response = api.systemGetAllHistorianRecords();

        // TODO: test validations
    }
    
    /**
     * Get all identities from the identity registry
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemGetAllIdentitiesTest() throws ApiException {
        // List<Object> response = api.systemGetAllIdentities();

        // TODO: test validations
    }
    
    /**
     * Get the specified Historian Record from the Historian
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemGetHistorianRecordByIDTest() throws ApiException {
        String id = null;
        // Object response = api.systemGetHistorianRecordByID(id);

        // TODO: test validations
    }
    
    /**
     * Get the specified identity from the identity registry
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemGetIdentityByIDTest() throws ApiException {
        String id = null;
        // Object response = api.systemGetIdentityByID(id);

        // TODO: test validations
    }
    
    /**
     * Issue an identity to the specified participant
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemIssueIdentityTest() throws ApiException {
        IssueIdentityRequest data = null;
        // File response = api.systemIssueIdentity(data);

        // TODO: test validations
    }
    
    /**
     * Test the connection to the business network
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemPingTest() throws ApiException {
        // PingResponse response = api.systemPing();

        // TODO: test validations
    }
    
    /**
     * Revoke the specified identity
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemRevokeIdentityTest() throws ApiException {
        String id = null;
        // api.systemRevokeIdentity(id);

        // TODO: test validations
    }
    
}
